package io.github.kodiitulip.toywars.client.animations;

import net.minecraft.client.render.animation.Animation;
import net.minecraft.client.render.animation.Animator;
import net.minecraft.client.render.animation.AnimationKeyframe;
import net.minecraft.client.render.animation.PartAnimation;

public class LivingToyAnimations {

	public static final Animation ATTACK = Animation.Builder.withLength(0.5f)
		.addPartAnimation("head",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0f, -0.7f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("head",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(4f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("body",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0f, -0.7f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("body",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(4f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_arm",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0f, -0.7f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_arm",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(0f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.2916767f, Animator.rotate(-62.57f, 57.15f, 25.84f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.rotate(-28.02f, -27.75f, -12.39f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_arm",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0f, -0.7f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_arm",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(-3.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("living_toy",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, -0.5f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_leg",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0.6f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_leg",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(5.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_leg",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0.6f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_leg",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(-4.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR))).build();
	public static final Animation IDLE = Animation.Builder.withLength(1f).looping()
		.addPartAnimation("head",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0f, -0.7f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.translate(0f, -0.3f, -0.9f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.translate(0f, 0f, -0.7f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("head",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(4f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.rotate(5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.rotate(4f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("body",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0f, -0.7f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.translate(0f, -0.3f, -0.9f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.translate(0f, 0f, -0.7f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("body",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(4f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.rotate(5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.rotate(4f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_arm",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0f, -0.7f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.translate(0f, -0.3f, -0.9f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.translate(0f, 0f, -0.7f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_arm",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(0f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.rotate(-1.01f, -0.26f, 2.99f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.rotate(0f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_arm",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0f, -0.7f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.translate(0f, -0.3f, -0.9f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.translate(0f, 0f, -0.7f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_arm",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(-3.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.rotate(-3f, 0.17f, -1.99f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.rotate(-3.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_leg",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0.6f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.translate(0f, 0.6f, -0.4f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.translate(0f, 0.6f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_leg",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(-4.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.rotate(-2f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.rotate(-4.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_leg",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0.6f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.translate(0f, 0.6f, -0.1f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.translate(0f, 0.6f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_leg",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(5.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.rotate(7.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.rotate(5.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("living_toy",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, -0.5f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.translate(0f, -0.3f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.translate(0f, -0.5f, 0f),
					PartAnimation.Interpolations.LINEAR))).build();
	public static final Animation WALK = Animation.Builder.withLength(1f).looping()
		.addPartAnimation("living_toy",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, -1.9f, 0f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.20834334f, Animator.translate(0f, -0.5f, 0f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.5f, Animator.translate(0f, -1.9f, 0f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.7083434f, Animator.translate(0f, -0.5f, 0f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(1f, Animator.translate(0f, -1.9f, 0f),
					PartAnimation.Interpolations.SPLINE)))
		.addPartAnimation("left_leg",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 2.7f, -2.8f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.125f, Animator.translate(0f, 1.48f, -1.45f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.5f, Animator.translate(0f, 1.5f, 1.4f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.625f, Animator.translate(0f, 1.83f, 0.35f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(1f, Animator.translate(0f, 2.7f, -2.8f),
					PartAnimation.Interpolations.SPLINE)))
		.addPartAnimation("left_leg",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(-8f, 0f, 0f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.125f, Animator.rotate(0f, 0f, 0f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.5f, Animator.rotate(16f, 0f, 0f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.625f, Animator.rotate(23f, 0f, 0f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(1f, Animator.rotate(-8f, 0f, 0f),
					PartAnimation.Interpolations.SPLINE)))
		.addPartAnimation("right_leg",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 1.5f, 1.4f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.125f, Animator.translate(0f, 1.83f, 0.35f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.5f, Animator.translate(0f, 2.7f, -2.8f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.625f, Animator.translate(0f, 1.48f, -1.45f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(1f, Animator.translate(0f, 1.5f, 1.4f),
					PartAnimation.Interpolations.SPLINE)))
		.addPartAnimation("right_leg",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(16f, 0f, 0f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.125f, Animator.rotate(23f, 0f, 0f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.5f, Animator.rotate(-8f, 0f, 0f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(0.625f, Animator.rotate(0f, 0f, 0f),
					PartAnimation.Interpolations.SPLINE),
				new AnimationKeyframe(1f, Animator.rotate(16f, 0f, 0f),
					PartAnimation.Interpolations.SPLINE)))
		.addPartAnimation("left_arm",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0.4f, -1.6f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.translate(0f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.translate(0f, 0.4f, -1.6f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_arm",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(20f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.rotate(-20f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.rotate(20f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_arm",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0.4f, -1.6f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.translate(0f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.translate(0f, 0.4f, -1.6f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_arm",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(-20f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.rotate(20f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.rotate(-20f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("body",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0.4f, -1.6f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.translate(0f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.translate(0f, 0.4f, -1.6f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("body",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(7.5f, -0.13f, 0.99f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.rotate(4.5f, 0.08f, -1f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.rotate(7.5f, -0.13f, 0.99f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("head",
			new PartAnimation(PartAnimation.AnimationTargets.TRANSLATE,
				new AnimationKeyframe(0f, Animator.translate(0f, 0.4f, -1.6f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.translate(0f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.translate(0f, 0.4f, -1.6f),
					PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("head",
			new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
				new AnimationKeyframe(0f, Animator.rotate(0.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(0.5f, Animator.rotate(2.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR),
				new AnimationKeyframe(1f, Animator.rotate(0.5f, 0f, 0f),
					PartAnimation.Interpolations.LINEAR))).build();
}
